/* LAVISHA ECOMMERCE HUB — customer catalogue + owner login + product manager */
const CONFIG={whatsapp:"917015066259",instagram:"lecommercehub",razorpayMe:"https://razorpay.me/@hitesh2507",storeName:"Lavisha Ecommerce Hub",currency:"₹"};
const starter=[
{id:1,name:"Classic Tote Bag",price:799,category:"Bags",emoji:"👜",badge:"Popular",image:"products/tote.svg",link:""},
{id:2,name:"Premium Watch",price:1299,category:"Accessories",emoji:"⌚",badge:"New",image:"products/watch.svg",link:""},
{id:3,name:"Beauty Gift Set",price:999,category:"Beauty",emoji:"🎁",badge:"Hot",image:"products/beauty.svg",link:""},
{id:4,name:"Cute Sneakers",price:1499,category:"Footwear",emoji:"👟",badge:"Trending",image:"products/sneakers.svg",link:""},
{id:5,name:"Mini Handbag",price:899,category:"Bags",emoji:"👛",badge:"New",image:"products/handbag.svg",link:""},
{id:6,name:"Fashion Sunglasses",price:599,category:"Accessories",emoji:"🕶️",badge:"Sale",image:"products/sunglasses.svg",link:""},
{id:7,name:"Perfume Collection",price:749,category:"Beauty",emoji:"🌸",badge:"Popular",image:"products/perfume.svg",link:""},
{id:8,name:"Casual Sandals",price:699,category:"Footwear",emoji:"🩴",badge:"New",image:"products/sandals.svg",link:""}
];
function cloneStarter(){return starter.map(p=>({...p}));}
function loadProducts(){try{const raw=localStorage.getItem("lavisha_products_v3");const saved=raw?JSON.parse(raw):null;return Array.isArray(saved)?saved:cloneStarter()}catch{return cloneStarter()}}
let products=loadProducts();let cart=[];try{cart=JSON.parse(localStorage.getItem("lavisha_cart_v3")||"[]")}catch{}
let activeCat="All",editingId=null,pendingProductImage="",isOwner=false;
const $=id=>document.getElementById(id);$("year").textContent=new Date().getFullYear();
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function money(n){return CONFIG.currency+Number(n||0).toLocaleString("en-IN")}
function safeUrl(url){try{const u=new URL(url);return ["http:","https:"].includes(u.protocol)?u.href:""}catch{return ""}}
function save(){localStorage.setItem("lavisha_products_v3",JSON.stringify(products));localStorage.setItem("lavisha_cart_v3",JSON.stringify(cart));updateCart()}
function updateCart(){$("cartCount").textContent=cart.reduce((s,i)=>s+i.qty,0)}
function imageHTML(p){const src=esc(p.image||"");const emoji=esc(p.emoji||"🛍️");return src?`<img class="product-img" src="${src}" alt="${esc(p.name)}" loading="lazy" onerror="this.onerror=null;this.src='products/placeholder.svg'">`:`<div class="image-fallback visible">${emoji}</div>`}
function render(){const cats=["All",...new Set(products.map(p=>p.category).filter(Boolean))];if(!cats.includes(activeCat))activeCat="All";$('categories').innerHTML=cats.map(c=>`<button class="chip ${c===activeCat?'active':''}" onclick="setCat(${JSON.stringify(c)})">${esc(c)}</button>`).join("");const q=($('search').value||"").toLowerCase().trim();const list=products.filter(p=>(activeCat==="All"||p.category===activeCat)&&(p.name+" "+p.category).toLowerCase().includes(q));$('products').innerHTML=list.length?list.map(p=>{const link=safeUrl(p.link);return `<article class="card"><div class="photo"><span class="badge">${esc(p.badge||"Featured")}</span>${imageHTML(p)}</div><div class="info"><span class="cat">${esc(p.category||"General")}</span><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><div class="actions"><button class="add" onclick="addCart(${p.id})">Add to Cart</button><button class="enq" onclick="enquire(${p.id})">Enquiry</button>${link?`<a class="linkBtn" href="${esc(link)}" target="_blank" rel="noopener">Product Link ↗</a>`:`<button class="linkBtn" onclick="enquire(${p.id})">Product Details</button>`}</div></div></article>`}).join(""):emptyCatalogue()}
function emptyCatalogue(){return `<div class="empty-catalogue"><div>🛍️</div><h3>No products found</h3><p>Try another search or category.</p><button class="btn primary" onclick="resetCatalogue()">Reset Catalogue</button></div>`}
function setCat(c){activeCat=c;render()}
function resetCatalogue(){if(!confirm("Restore the default Lavisha catalogue? This replaces products saved in this browser."))return;products=cloneStarter();cart=[];activeCat="All";$('search').value="";save();render();alert("Default catalogue restored successfully.")}
function addCart(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();openCart()}
function enquire(id){const p=products.find(x=>x.id===id);if(!p)return;whatsapp(`Hello Lavisha Ecommerce Hub, I want to enquire about ${p.name} (${money(p.price)}). Please share availability and details.`)}
function whatsapp(msg){const n=CONFIG.whatsapp.replace(/\D/g,"");if(n.length<10){alert("Owner: add your WhatsApp number in script.js first.");return}window.open("https://wa.me/"+n+"?text="+encodeURIComponent(msg),"_blank","noopener")}
function openCart(){const items=cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="cartItem"><span><b>${esc(p.name)}</b><br>${money(p.price)} × ${i.qty}</span><span class="qty"><button onclick="qty(${p.id},-1)">−</button> ${i.qty} <button onclick="qty(${p.id},1)">+</button></span></div>`:""}).join("");const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);show(`<h2>🛒 Your Cart</h2>${items||"<p>Your cart is empty.</p>"}${cart.length?`<div class="total">Total: ${money(total)}</div><div class="modalActions"><button class="btn primary" onclick="checkoutWhatsApp()">Order on WhatsApp</button><button class="btn white" onclick="payOnline()">Pay Online</button></div>`:""}`)}
function qty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save();openCart()}
function orderText(){return cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`${p.name} × ${i.qty} = ${money(p.price*i.qty)}`:""}).filter(Boolean).join("\n")}
function checkoutWhatsApp(){const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);whatsapp(`Hello Lavisha Ecommerce Hub, I want to place this order:\n\n${orderText()}\n\nTotal: ${money(total)}\nPlease confirm availability, delivery charges and address details.`)}
function payOnline(){window.open(CONFIG.razorpayMe,"_blank","noopener")}
function openEnquiry(){show(`<h2>💬 Product Enquiry</h2><p>Send your question directly to Lavisha on WhatsApp.</p><div class="form"><input id="enqName" placeholder="Your name"><input id="enqProduct" placeholder="Product / item you're interested in"><textarea id="enqMsg" placeholder="Your question"></textarea><button class="btn primary" onclick="sendEnquiry()">Send Enquiry on WhatsApp →</button></div>`)}
function sendEnquiry(){const n=$("enqName").value.trim(),p=$("enqProduct").value.trim(),m=$("enqMsg").value.trim();whatsapp(`Hello Lavisha Ecommerce Hub!\nName: ${n||"Customer"}\nProduct: ${p||"General enquiry"}\nMessage: ${m||"Please share details."}`)}
function openLogin(){if(isOwner){openOwner();return}show(`<div class="loginBox"><div class="loginIcon">🔐</div><h2>Owner Login</h2><p>Sign in to manage your Lavisha catalogue.</p><div class="form"><input id="loginUser" autocomplete="username" placeholder="Username"><input id="loginPass" type="password" autocomplete="current-password" placeholder="Password" onkeydown="if(event.key==='Enter')loginOwner()"><button class="btn primary" onclick="loginOwner()">Login to Owner Panel</button></div><small class="loginHint">Default login: <b>owner</b> / <b>1234</b>. Change it from the Owner Panel.</small></div>`)}
function loginOwner(){const u=$("loginUser").value.trim(),p=$("loginPass").value;const cu=localStorage.getItem("lavisha_owner_user")||"owner",cp=localStorage.getItem("lavisha_owner_pass")||"1234";if(u===cu&&p===cp){isOwner=true;closeModal();openOwner()}else alert("Incorrect username or password.")}
function logoutOwner(){isOwner=false;closeModal();alert("Owner logged out.")}
function openOwner(){if(!isOwner){openLogin();return}show(`<div class="ownerHeader"><div><span class="eyebrow">OWNER PANEL</span><h2>⚙ Catalogue Manager</h2></div><button class="btn white" onclick="logoutOwner()">Log out</button></div><p class="panelNote">Manage your catalogue on this device. Add, edit and remove products, upload photos, and add a product link.</p><div class="ownerTabs"><button class="tab active">Products (${products.length})</button><button class="tab" onclick="scrollOwnerTo('storeSettings')">Store Settings</button></div><div class="form"><input id="pn" placeholder="Product name"><div class="row"><input id="pp" type="number" min="0" placeholder="Price"><input id="pc" placeholder="Category"></div><div class="row"><input id="pe" placeholder="Emoji fallback e.g. 👜"><input id="pb" placeholder="Badge e.g. New"></div><label class="uploadLabel">📷 Upload product photo<input id="pfile" type="file" accept="image/*" onchange="previewProductImage(event)"></label><div id="uploadPreview" class="uploadPreview"><span>No photo selected</span></div><input id="pi" placeholder="Or paste image URL (https://...)"/><input id="pl" placeholder="Product link (https://...) — where customer can buy/view it"><div class="modalActions"><button class="btn primary" onclick="saveProduct()">＋ ${editingId?'Update':'Add'} Product</button><button class="btn white" onclick="clearProductForm()">Clear</button><button class="btn white" onclick="resetCatalogue()">↻ Restore Defaults</button></div></div><h3>Current Catalogue</h3><div class="ownerList">${products.map(p=>`<div class="ownerItem"><div class="ownerProduct"><img src="${esc(p.image||'products/placeholder.svg')}" onerror="this.src='products/placeholder.svg'" alt=""><div><b>${esc(p.name)}</b><small>${money(p.price)} · ${esc(p.category||'General')}</small>${safeUrl(p.link)?`<a href="${esc(safeUrl(p.link))}" target="_blank" rel="noopener">Product Link ↗</a>`:`<small>No product link</small>`}</div></div><div class="ownerItemBtns"><button class="editBtn" onclick="editProduct(${p.id})">Edit</button><button class="danger" onclick="removeProduct(${p.id})">Remove</button></div></div>`).join("")}</div><div id="storeSettings" class="settingsCard"><h3>Store Settings</h3><p>Instagram: @${esc(CONFIG.instagram)}<br>Payment link: Razorpay.me<br><small>Login and catalogue data are stored in this browser. For multi-device/cloud management, a real database and secure authentication are required.</small></p><button class="btn white" onclick="changeOwnerLogin()">Change Owner Login</button></div>`)}
function scrollOwnerTo(id){const el=$(id);if(el)el.scrollIntoView({behavior:'smooth'})}
function clearProductForm(){editingId=null;pendingProductImage="";['pn','pp','pc','pe','pb','pi','pl'].forEach(id=>{const el=$(id);if(el)el.value=""});const f=$("pfile");if(f)f.value="";const b=$("uploadPreview");if(b)b.innerHTML="<span>No photo selected</span>";const btn=document.querySelector('.modalActions .primary');if(btn)btn.textContent="＋ Add Product"}
function previewProductImage(event){const file=event.target.files&&event.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){alert('Please choose an image file.');event.target.value='';return}if(file.size>4*1024*1024){alert('Please choose an image smaller than 4 MB.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);pendingProductImage=c.toDataURL('image/jpeg',.78);$("uploadPreview").innerHTML=`<img src="${pendingProductImage}" alt="Product preview"><button type="button" class="removePreview" onclick="clearProductImage()">×</button>`};img.src=reader.result};reader.readAsDataURL(file)}
function clearProductImage(){pendingProductImage="";const f=$("pfile");if(f)f.value="";const box=$("uploadPreview");if(box)box.innerHTML="<span>No photo selected</span>"}
function saveProduct(){const name=$("pn").value.trim(),price=Number($("pp").value),cat=$("pc").value.trim()||"General",emoji=$("pe").value.trim()||"🛍️",badge=$("pb").value.trim()||"New",urlImage=safeUrl($("pi").value.trim()),link=safeUrl($("pl").value.trim());if(!name||!Number.isFinite(price)||price<0){alert('Enter a valid product name and price.');return}const old=editingId?products.find(p=>p.id===editingId):null;const image=pendingProductImage||urlImage||old?.image||'products/placeholder.svg';if(editingId){products=products.map(p=>p.id===editingId?{...p,name,price,category:cat,emoji,badge,image,link}:p)}else{products.unshift({id:Date.now(),name,price,category:cat,emoji,badge,image,link})}try{save();render();const wasEdit=!!editingId;editingId=null;pendingProductImage="";openOwner();alert(wasEdit?'Product updated successfully.':'Product added successfully.')}catch(e){alert('Could not save this image. Try a smaller photo.')}}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editingId=id;openOwner();setTimeout(()=>{if($("pn")){$("pn").value=p.name;$('pp').value=p.price;$('pc').value=p.category||'';$('pe').value=p.emoji||'';$('pb').value=p.badge||'';$('pi').value=(p.image||'').startsWith('data:')?'':(p.image||'');$('pl').value=p.link||'';pendingProductImage=(p.image||'').startsWith('data:')?p.image:'';$('uploadPreview').innerHTML=pendingProductImage?`<img src="${pendingProductImage}" alt="Product preview"><button type="button" class="removePreview" onclick="clearProductImage()">×</button>`:`<img src="${esc(p.image||'products/placeholder.svg')}" alt="Current image" onerror="this.src='products/placeholder.svg'">`;const btn=document.querySelector('.modalActions .primary');if(btn)btn.textContent='✓ Update Product';}},0)}
function removeProduct(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`Remove “${p.name}” from the catalogue?`))return;products=products.filter(x=>x.id!==id);cart=cart.filter(i=>i.id!==id);save();render();openOwner()}
function changeOwnerLogin(){show(`<h2>🔑 Change Owner Login</h2><p>Set a new username and password for this browser.</p><div class="form"><input id="newOwnerUser" placeholder="New username"><input id="newOwnerPass" type="password" placeholder="New password"><input id="newOwnerPass2" type="password" placeholder="Confirm password"><button class="btn primary" onclick="saveOwnerLogin()">Save Login</button></div>`)}
function saveOwnerLogin(){const u=$("newOwnerUser").value.trim(),p=$("newOwnerPass").value,p2=$("newOwnerPass2").value;if(!u||p.length<4||p!==p2){alert('Enter a username and a password of at least 4 characters; passwords must match.');return}localStorage.setItem('lavisha_owner_user',u);localStorage.setItem('lavisha_owner_pass',p);alert('Owner login updated on this browser.');openOwner()}
function show(html){$("modalContent").innerHTML=html;$("modal").classList.add('show');document.body.classList.add('modalOpen')}
function closeModal(){$("modal").classList.remove('show');document.body.classList.remove('modalOpen')}
render();updateCart();
